### ISSUE TITLE
Functional and Non-Functional

### ISSUE THREAD

**Issue by udeshika0417** [udeshika0417/SmartDoorUnlockSystem#3]
Complete the Functional and Non functional Requirement part in SRS Document

**Comment by gkdanuka** [comment]
Completed the Functional and Non-Functional requirements

**Comment by randisasanka** [comment]
Completed the functional & non-functional requirements part

**Comment by RuwanRun** [comment]
Completed functional and non-functional requirement part.

**Comment by Miyuranga305** [comment]
Completed Functional and Non-Funtional requirement part.
